language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'rvm use --default 2.0.0'
  - 'gem update --system'
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
